# Generated by Django 5.1.3 on 2024-12-01 15:50

import GameMax.app_users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_age_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', validators=[GameMax.app_users.validators.MaxFileSizeValidator()]),
        ),
    ]
