# Generated by Django 5.1.3 on 2024-12-02 15:49

import GameMax.app_users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Your Name Must Be At Least 2 Characters Long.'), GameMax.app_users.validators.OnlyLettersDigitsUnderscoresValidator()]),
        ),
    ]
