# Generated by Django 5.1.3 on 2024-12-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'User'},
        ),
    ]
