# Generated by Django 5.1.3 on 2024-12-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_appuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this Email already exists.'}, max_length=254, unique=True),
        ),
    ]
