# Generated by Django 5.1.3 on 2024-12-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_remove_order_games'),
        ('shop', '0005_remove_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='games',
            field=models.ManyToManyField(to='shop.game'),
        ),
    ]
