# Generated by Django 5.1.3 on 2024-12-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_review'),
        ('shop', '0005_remove_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.game'),
        ),
    ]
